SELECT DISTINCT O1.USER_ID, O1.PRODUCT_ID
FROM ONLINE_SALE AS O1, ONLINE_SALE AS O2
WHERE O1.USER_ID=O2.USER_ID AND O1.PRODUCT_ID=O2.PRODUCT_ID AND O1.SALES_DATE!=O2.SALES_DATE
ORDER BY O1.USER_ID ASC, O1.PRODUCT_ID DESC