SELECT DISTINCT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I, ITEM_TREE AS T
WHERE I.ITEM_ID IN (SELECT DISTINCT T.ITEM_ID
                FROM ITEM_INFO AS I, ITEM_TREE AS T
                WHERE I.ITEM_ID=T.PARENT_ITEM_ID AND I.RARITY='RARE')
ORDER BY I.ITEM_ID DESC;