SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (I.MAX_OF_YEAR-E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA AS E
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_OF_YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS I
ON YEAR(E.DIFFERENTIATION_DATE)=I.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC