SELECT I.ID, FISH_NAME, MAX_LENGTH AS LENGTH
FROM FISH_INFO AS I
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
    ) AS N
ON I.FISH_TYPE=N.FISH_TYPE AND I.LENGTH=N.MAX_LENGTH
JOIN FISH_NAME_INFO AS O ON I.FISH_TYPE=O.FISH_TYPE
ORDER BY ID ASC;